#!/bin/bash

set -euo pipefail

function cd_to_root() {
    year=
    while [[ ! -d .git && $PWD != "/" ]]; do
        year=$(basename $PWD)
        cd ..
    done
    if [[ $PWD == "/" ]]; then
        echo "error: Not inside the advent_of_code git repository" 1>&2
        exit 1
    fi
    echo $year
}

function get_next_day() {
    cd_to_root &>/dev/null
    max_day=0
    for day in $(ls "$1" | grep '^day[0-9]\+$' | sed 's/day//')
    do
        max_day=$(( $day > $max_day ? $day : $max_day ))
    done
    expr $max_day + 1
}

function usage() {
    echo "usage: start_day <year> <day>" 1>&2
    exit 1
}

if [[ $# == 2 ]]; then
    YEAR=$1
    DAY=$2
elif [[ $# == 1 ]]; then
    YEAR=$(cd_to_root)
    DAY=$1
elif [[ $# == 0 ]]; then
    YEAR=$(cd_to_root)
    DAY=$(get_next_day $YEAR)
else
    usage
fi

if ! [[ $YEAR =~ 20[0-9]{2} ]]; then
    echo "error: invalid year: $YEAR" 1>&2
    usage
fi
if ! [[ $DAY =~ [1-9]|1[0-9]|2[0-5] ]]; then
    echo "error: invalid day: $DAY" 1>&2
    usage
fi
echo "Day $DAY $YEAR"

cd_to_root &> /dev/null

mkdir -p $YEAR/day$DAY/
cd $YEAR/day$DAY/
mkdir -p src/
if [ ! -f Cargo.toml ]; then
    cat > Cargo.toml <<EOF
[package]
name = "day$DAY-$YEAR"
version = "0.1.0"
authors = ["$(git config user.name) <$(git config user.email)>"]
edition = "2018"

[dependencies]
EOF
fi

# Share target dirs to avoid recompiling common dependencies like regex
ln -sf ../../target/ target
if [ ! -f src/main.rs ]; then
    cat > src/main.rs <<EOF
use std::fmt::Display;
use std::io::{self, Read};

fn part1(input: &str) -> impl Display {
    "FIXME"
}

fn part2(input: &str) -> impl Display {
    "FIXME"
}

fn main() {
    let mut input = String::new();
    io::stdin().read_to_string(&mut input).unwrap();

    println!("{}", part1(&input));
    println!("{}", part2(&input));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_part1() {
        // FIXME
    }

    #[test]
    fn test_part2() {
        // FIXME
    }
}
EOF
fi
wget --no-verbose --load-cookies ../../cookies.txt  https://adventofcode.com/$YEAR/day/$DAY/input -O input
