#!/bin/bash

set -euo pipefail

function cd_to_root() {
    year=
    while [[ ! -d .git && $PWD != "/" ]]; do
        year=$(basename $PWD)
        cd ..
    done
    if [[ $PWD == "/" ]]; then
        echo "error: Not inside the advent_of_code git repository" 1>&2
        exit 1
    fi
    echo $year
}

function usage() {
    echo "usage: start_day <year> <day>" 1>&2
    exit 1
}

if [[ $# == 2 ]]; then
    YEAR=$1
    DAY=$2
elif [[ $# == 1 ]]; then
    DAY=$1
    YEAR=$(cd_to_root)
    if [[ $YEAR == "" ]]; then
        echo "error: when year is not specified, must be in a child directory of the ear" 1>&2
        exit 1
    fi
else
    usage
fi

if ! [[ $YEAR =~ 20[0-9]{2} ]]; then
    echo "error: invalid year: $YEAR" 1>&2
    usage
fi
if ! [[ $DAY =~ [1-9]|1[0-9]|2[0-5] ]]; then
    echo "error: invalid day: $DAY" 1>&2
    usage
fi

cd_to_root &> /dev/null

mkdir -p $YEAR/day$DAY/
cd $YEAR/day$DAY/
mkdir -p src/
cat > Cargo.toml <<EOF
[package]
name = "day$DAY-$YEAR"
version = "0.1.0"
authors = ["$(git config user.name) <$(git config user.email)>"]
edition = "2018"

[dependencies]
EOF
# Share target dirs to avoid recompiling common dependencies like regex
ln -sf ../../target/ target
cat > src/main.rs <<EOF
use std::io::{self, Read};

fn part1(input: &str) -> usize {
    0 // FIXME
}

fn part2(input: &str) -> usize {
    0 // FIXME
}

fn main() {
    let mut input = String::new();
    io::stdin().read_to_string(&mut input).unwrap();

    println!("{}", part1(&input));
    println!("{}", part2(&input));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_part1() {
        // FIXME
    }

    #[test]
    fn test_part2() {
        // FIXME
    }
}
EOF
wget --no-verbose --load-cookies ../../cookies.txt  https://adventofcode.com/$YEAR/day/$DAY/input -O input
