[package]
name = "day11-2016"
version = "0.1.0"
authors = ["Greg Rogers <greg.r.rogers@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "0.3"
lazy_static = "1"
regex = "1"
string-interner = "0.7"
