#!/bin/bash
set -euo pipefail
for dir in $(find $(dirname $0) -name Cargo.toml | xargs dirname | sort -V)
do
    pushd $dir >/dev/null
    cargo test --release
    if [ -f input ]; then
        cargo run --release < input
    fi
    popd >/dev/null
done
